		<!--MAIN CONTENT-->
		<main class="container">
			<section id="noel">
				<?php foreach($promo as $prom): ?>
				<h1><?= $prom['titre_promo']?></h1>
				<img src="<?= $prom['image_promo']?>" alt="Offre spéciale pour noel ! Dès 45€ d'achat, le photophore de noël vous sera offert. Et dès 85€ un thé vert au prune et coing de 100 gramme vous sera offert" />
				<small><?= $prom['legende_promo']?></small>
				<?php endforeach; ?>
				
			</section>
			<section id="slider">
				<div>
					<ul class="slides">
						<?php foreach ($sliders as $index=>$slider): ?>
						<li class="<?= ($index==0)?'visible':'block' ?>"><img src="<?= $slider["image_slider"] ?>" alt="Retrouvez toute nos idées cadeaux pour les fêtes de noël" /></li>
						<?php endforeach; ?>
					
					</ul>
				</div>
			</section>
			<section id="categorie" class="animate__animated animate__fadeInLeft">
				<h2><span>Choisissez votre thé</span></h2>
				
				<?php foreach($cat as $cate): ?>
				<a href="#">
					<img src="<?= $cate['image_cat'] ?>"alt="Tasse de thé noir" />
					<h3><?= $cate['nom_cat'] ?></h3>
				</a>
				<?php endforeach; ?>
			
			</section>
			<section id="tea">
				<article id="new">
					<h2><span>Notre nouveauté</span></h2>
					<img src="<?= $new['image_the'] ?>" alt="Thé du Hammam" />
					<h3><?= $new['titre_the'] ?></h3>
					<p><?= $new['desc_the'] ?></p>
					<section class="price">
						<p>À partir de <strong><?= $new['prix'] ?>Pieces d'or</strong></p>
					</section>
					<a class="btn" href="#">Voir ce produit</a>
				</article>
				<article id="best">
					<h2><span>Notre best-seller</span></h2>
					<img src="<?= $best['image_the'] ?>" alt="Infustion Herboriste" />
					<h3><?= $best['titre_the'] ?></h3>
					<p><?= $best['desc_the'] ?></p>
					<section class="price">
						<p>À partir de <strong><?= $best['prix'] ?>Kamas</strong></p>
					</section>
					<a class="btn" href="#">Voir ce produit</a>
				</article>
				<article id="crush">
					<h2><span>Notre coup de coeur</span></h2>
					<img src="<?= $cdc['image_the'] ?>" alt="Blue of London" />
					<h3><?= $cdc['titre_the'] ?></h3>
					<p><?= $cdc['desc_the'] ?>.</p>
					<section class="price">
						<p>À partir de <strong><?= $cdc['prix'] ?>€</strong></p>
					</section>
					<a class="btn" href="product.html">Voir ce produit</a>
				</article>
			</section>
		</main>
		<script type="text/javascript" src="public/js/slider.js"></script>
