<!DOCTYPE html>
<html>
	<head>
		<title>Module 12 - Cup of Tea</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- CSS Vendor -->
		<link rel="stylesheet" href="public/css/font-awesome.min.css">
		
		<!-- CSS Perso -->
		<link rel="stylesheet" href="public/css/normalize.css">
		<link rel="stylesheet" href="public/css/base.css">
		<link rel="stylesheet" href="public/css/style.css">
		<!-- Perso JS -->
		<script src="public/js/jquery.js"></script>
		<script src="public/js/jquery.flexslider-min.js"></script>
		<script
              src="https://code.jquery.com/jquery-3.5.1.min.js"
              integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
              crossorigin="anonymous"></script>
              
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		
		</script>
	</head>
	<body>
		<!--HEADER-->
		<header>
			<img class="ribbon" src="public/img/ribbon.svg" alt="élu meilleur thé en 2016" />
			<section id="topbar">Livraison offerte à partir de 65€ d'achat !</section>
			<div class="container">
				<section id="logo">
					<a href="index.php?page=accueil">
						<img src="public/img/logo.png" alt="Logo de Cup of Tea" />
					</a>
					<section id="cart">
						<?php if(!isset($_SESSION['user'])): ?>
						<a href="index.php?page=register" class="myButton">Creer un Comtpe</a>
						<a href="index.php?page=connect" class="myButton">Se Konnecthé</a>
						<?php else: ?>
						<a id="command" href="index.php?page=panier">Mon panier</a>
						<strong id="valeurPanier">0,00€</strong>
						
						<a href="index.php?page=disconnect" class="myButton">se deconnecter</a>
						 <?php endif; ?>
						
					</section>
				</section>
				<nav>
					<a href="listing-product.html">Thés</a>
					<a href="#">Grands crus</a>
					<a href="#">Accessoires</a>
					<a href="#">Epicerie</a>
					<a href="about.html">Notre histoire</a>
				</nav>
			</div>
		</header>
	<?php include $template; ?>
	
	
		<footer>
			<section id="info">
				<article>
					<i class="fa fa-lock"></i>
					<small>Paiement sécurisé</small>
				</article>
				<article>
					<i class="fa fa-truck"></i>
					<small>Ma livraison offerte</small>
				</article>
				<article>
					<i class="fa fa-money"></i>
					<small>Carte de fidélité</small>
				</article>
				<article>
					<i class="fa fa-phone"></i>
					<small>Service client</small>
				</article>
				<article>
					<i class="fa fa-check-circle"></i>
					<small>Garantie qualité</small>
				</article>
			</section>
			<section id="bottombar">
				<article>
					<h2>Découvrir Cup of Tea</h2>
					<ul>
						<li>Notre histoire</li>
		    			<li>Nos boutiques</li>
		    			<li>Le Thé de A à Z</li>
		    			<li>Espace clients professionnels</li>
		    			<li>Recrutement</li>
		    			<li>Contactez-nous !</li>
		    			<li>L'École du Thé</li>
					</ul>
				</article>
				<article>
					<h2>Commandez en ligne</h2>
					<ul>
						<li>Première visite</li>
		    			<li>Aide - FAQ</li>
		    			<li>Service client</li>
		    			<li>Suivre ma commande</li>
		    			<li>Conditions générales de vente</li>
		    			<li>Informations légales</li>
					</ul>
				</article>
				<article>
					<h2>Suivez-nous !</h2>
					<ul>
						<li>Notre histoire</li>
		    			<li>Nos boutiques</li>
		    			<li>Le Thé de A à Z</li>
		    			<li>Espace clients professionnels</li>
					</ul>
				</article>
			</section>
			<small id="licence">
				   <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" style="border-width:0" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png" /></a><br /><span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants, Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br />Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="http://www.justine-muller.fr">Justine Muller</a>.
				   
			</small>
		</footer>
		
	</body>
</html>