
    <article>
            <h1><?= $thesModel['titre_the'] ?> </h1>
            <p> <?=  $thesModel['sousTitre_the']?></p>
            <p> <?=  $thesModel['ref_the']?></p>
            <p> <?=  $thesModel['desc_the']?></p>
            
            <img src="<?= $thesModel['image_the'] ?>" alt="">
            <form>
                <select id="price">
            <option disabled>--Please choose an option--</option>
        <?php  foreach($thesPrice as $price): ?>
            <option data-price="<?=  $price['prix']?>" value="<?=  $price['poid']?>" id="poid"><?=  $price['poid']?></option>
        <?php endforeach; ?>
    
           
    
            </select>
            </form>
             <p id="prix"></p>
            <a  data-id="<?= $thesModel['id_the'] ?>" id="test"><button>Ajouter au panier</button></a>
            
    </article>
    <?//php if(isset($_SESSION['user'])): ?>

    <script type="text/javascript" src="public/js/produit.js"></script>
     <?//php endif; ?>