
<link rel="stylesheet" href="public/css/style.css" type="text/css" />
<div class="containerForm">
<form method="POST">
    <p>
        <label for="firstname">Prénom</label>
        <input type="text" name="firstname" placeholder="prenom"  />
        <label for="name">Nom</label>
        <input type="text" name="name" placeholder="nom" />
        <label for="birthdate">Date de naissance</label>
        <input type="date" name="birthdate" placeholder="date de naissance" />
    </p>
    <p>
        <label for="phone">Numéro de téléphone</label>
        <input type="tel" id="phone" name="phone" pattern="[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}[0-9]{2}" placeholder="0633705714">
        <label for="adress">Adresse</label>
        <input type="text" name="adress" placeholder="adresse" />
        <label for="zipcode">Code postal</label>
        <input id="zip" name="zipcode" type="text" pattern="[0-9]*" placeholder="code postal">
        <label for="city">Ville</label>
        <input type="text" name="city" placeholder="ville" />
    </p>
    <p>
        <label for="email">Adresse mail</label>
        <input type="email" name="email" placeholder="e-m@il" />
     </p>
     <p id="passwords">
        <label for="password">Mot de passe</label>
        
        <input type="password" name="pass" id="pass"/>
        <label for="password2" id="passs">Vérification mot de passe</label>
        <input type = "password" name="vpass" id="vpass"/>
    </p>    
        
        <span id="errors"></span>
        
        <a href="index.php?page=connect"><input type="submit" id="submit" value="inscription!"></a>
</form>

<script type="text/javascript" src="public/js/mdp.js"></script>